install.packages("ggplot2")
library(ggplot2)
data(diamonds)
head(diamonds)
diamantes = diamonds[ ,c(1,5,6,7,8,9,10)]
diamantes0 = scale(diamantes)
diamantes0 <- as.data.frame(diamantes0)
pairs(diamantes0, col= "blue", main="Matriz de dispersi?n de las variables num?ricas")
modelo1 = lm(price ~ carat + depth + table + x + y + z, data = diamantes0)
summary(modelo1)
plot(modelo1, which =1)
modelo2 = lm(price ~ carat + depth + table + x, data = diamantes)
summary(modelo2)
plot(modelo2, which=1)
modelo3 = lm(price ~ depth + table + x + y + z, data = diamantes)
summary(modelo3)
plot(modelo3, which=1)
angulo <- acos(sqrt(.8592))
angulo * 180/pi